import IShipDesign from "@/type/data/IShipDesign"
import { RESOURCE_TYPES } from "./ResourcesService"

const getAllShips: () => { [name: string]: IShipDesign } = () => ({
  apollo: {
    name: "Apollo",
    class: "apollo",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.HYDROGENE]: 100,
    },
    img: "/images/enhanced/apollo.png",
    emplacement: 10,
    fuelSpace: 25_000,
    multiplier: {
      warp: 1,
      impulse: 1,
      conso: 1,
    },
    baseCoque: 100,
  },
  arc: {
    name: "Arc",
    class: "arc",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
      [RESOURCE_TYPES.HYDROGENE]: 100,
      [RESOURCE_TYPES.FER]: 100,
    },
    img: "/images/enhanced/arc.png",
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  artemis: {
    name: "Artemis",
    class: "artemis",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    img: "/images/enhanced/artemis.png",
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  athena: {
    name: "Athena",
    class: "athena",
    img: "/images/enhanced/athena.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  atlas: {
    name: "Atlas",
    class: "atlas",
    img: "/images/enhanced/atlas.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  centaure: {
    name: "Centaure",
    class: "centaure",
    img: "/images/enhanced/centaure.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  chasseur: {
    name: "Chasseur",
    class: "chasseur",
    img: "/images/enhanced/chasseur.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  croiseur_intergalactique: {
    name: "Croiseur Intergalactique",
    class: "croiseur_intergalactique",
    img: "/images/enhanced/croiseur_intergalactique.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  croiseur: {
    name: "Croiseur",
    class: "croiseur",
    img: "/images/enhanced/croiseur.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  destroyer: {
    name: "Destroyer",
    class: "destroyer",
    img: "/images/enhanced/destroyer.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  dionysos: {
    name: "Dionysos",
    class: "dionysos",
    img: "/images/enhanced/dionysos.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  docker: {
    name: "Docker",
    class: "docker",
    img: "/images/enhanced/docker.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  enigma: {
    name: "Enigma",
    class: "enigma",
    img: "/images/enhanced/enigma.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  eros: {
    name: "Eros",
    class: "eros",
    img: "/images/enhanced/eros.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  fregate: {
    name: "Fregate",
    class: "fregate",
    img: "/images/enhanced/fregate.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  frozen: {
    name: "Frozen",
    class: "frozen",
    img: "/images/enhanced/frozen.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  helios: {
    name: "Helios",
    class: "helios",
    img: "/images/enhanced/helios.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  hera: {
    name: "Hera",
    class: "hera",
    img: "/images/enhanced/hera.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  hercules: {
    name: "Hercules",
    class: "hercules",
    img: "/images/enhanced/hercules.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  hermes: {
    name: "Hermes",
    class: "hermes",
    img: "/images/enhanced/hermes.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  intercepteur: {
    name: "Intercepteur",
    class: "intercepteur",
    img: "/images/enhanced/intercepteur.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  karfus: {
    name: "Karfus",
    class: "karfus",
    img: "/images/enhanced/karfus.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  legend: {
    name: "Legend",
    class: "legend",
    img: "/images/enhanced/legend.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  leviathan: {
    name: "Leviathan",
    class: "leviathan",
    img: "/images/enhanced/leviathan.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  loki: {
    name: "Loki",
    class: "loki",
    img: "/images/enhanced/loki.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  luna: {
    name: "Luna",
    class: "luna",
    img: "/images/enhanced/luna.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  mega_transporteur: {
    name: "Mega-Transporteur",
    class: "mega-transporteur",
    img: "/images/enhanced/mega_transporteur.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  minotaure: {
    name: "Minotaure",
    class: "minotaure",
    img: "/images/enhanced/minotaure.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  navette: {
    name: "Navette",
    class: "navette",
    img: "/images/enhanced/navette.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  nimbus: {
    name: "Nimbus",
    class: "nimbus",
    img: "/images/enhanced/nimbus.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  oblirator: {
    name: "Oblirator",
    class: "oblirator",
    img: "/images/enhanced/oblirator.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  odin: {
    name: "Odin",
    class: "odin",
    img: "/images/enhanced/odin.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  pallas: {
    name: "Pallas",
    class: "pallas",
    img: "/images/enhanced/pallas.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  patrouilleur: {
    name: "Patrouilleur",
    class: "patrouilleur",
    img: "/images/enhanced/patrouilleur.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  proleyend: {
    name: "Proleyend",
    class: "proleyend",
    img: "/images/enhanced/proleyend.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  proteus: {
    name: "Proteus",
    class: "proteus",
    img: "/images/enhanced/proteus.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  proto: {
    name: "Proto",
    class: "proto",
    img: "/images/enhanced/proto.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  saracen: {
    name: "Saracen",
    class: "saracen",
    img: "/images/enhanced/saracen.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  sonde: {
    name: "Sonde",
    class: "sonde",
    img: "/images/enhanced/sonde.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  station: {
    name: "Station",
    class: "station",
    img: "/images/enhanced/station.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  tethys: {
    name: "Tethys",
    class: "tethys",
    img: "/images/enhanced/tethys.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  thor: {
    name: "Thor",
    class: "thor",
    img: "/images/enhanced/thor.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  titan: {
    name: "Titan",
    class: "titan",
    img: "/images/enhanced/titan.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  transporteur: {
    name: "Transporteur",
    class: "transporteur",
    img: "/images/enhanced/transporteur.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  triton: {
    name: "Triton",
    class: "triton",
    img: "/images/enhanced/triton.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  tyran: {
    name: "Tyran",
    class: "tyran",
    img: "/images/enhanced/tyran.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  valkyrie: {
    name: "Valkyrie",
    class: "valkyrie",
    img: "/images/enhanced/valkyrie.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  virus: {
    name: "Virus",
    class: "virus",
    img: "/images/enhanced/virus.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  vortex: {
    name: "Vortex",
    class: "vortex",
    img: "/images/enhanced/vortex.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  voyager: {
    name: "Voyager",
    class: "voyager",
    img: "/images/enhanced/voyager.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  zeus: {
    name: "Zeus",
    class: "zeus",
    img: "/images/enhanced/zeus.png",
    cost: {
      [RESOURCE_TYPES.TITANE]: 500,
      [RESOURCE_TYPES.CUIVRE]: 500,
      [RESOURCE_TYPES.AZOTE]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
})

export default {
  getAllShips,
}
