import GlobalStyle from "@/ui/fondations/GlobalStyle";
import AppBarMenu from "@/ui/organisms/Bars/AppBarMenu";
import Modals from "@/ui/organisms/Modals/Modals";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./_Providers/Providers";
import "./globals.css";
import { ChildrenContainer } from "./baseCss";
import LeftSideBar from "@/ui/organisms/Bars/LeftSideBar";
import RightSideBar from "@/ui/organisms/Bars/RightSideBar";
import BottomTaskBar from "@/ui/organisms/Bars/BottomTaskBar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<Providers>
					<GlobalStyle />
					<Modals />
					<AppBarMenu />
					<LeftSideBar />
					<RightSideBar />
					<BottomTaskBar />
					<ChildrenContainer>{children}</ChildrenContainer>
				</Providers>
			</body>
		</html>
	);
}
