import IShip from "../type/IShip"
import IShipDesign from "../type/IShipDesign"
import {
  TITANE,
  HYDROGENE,
  AZOTE,
  ALUMINUM,
  CUIVRE,
  FER,
  URANIUM,
  SILICIUM,
} from "./ResourcesService"

const getAllShips: () => { [name: string]: IShipDesign } = () => ({
  apollo: {
    name: "Apollo",
    class: "apollo",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [HYDROGENE.name]: 100,
    },
    img: "/images/enhanced/apollo.jpg",
    emplacement: 10,
    fuelSpace: 25_000,
    multiplier: {
      warp: 1,
      impulse: 1,
      conso: 1,
    },
    baseCoque: 100,
  },
  arc: {
    name: "Arc",
    class: "arc",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
      [HYDROGENE.name]: 100,
      [FER.name]: 100,
    },
    img: "/images/enhanced/arc.jpg",
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  artemis: {
    name: "Artemis",
    class: "artemis",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    img: "/images/enhanced/artemis.jpg",
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  athena: {
    name: "Athena",
    class: "athena",
    img: "/images/enhanced/athena.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  atlas: {
    name: "Atlas",
    class: "atlas",
    img: "/images/enhanced/atlas.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  centaure: {
    name: "Centaure",
    class: "centaure",
    img: "/images/enhanced/centaure.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  chasseur: {
    name: "Chasseur",
    class: "chasseur",
    img: "/images/enhanced/chasseur.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  croiseur_intergalactique: {
    name: "Croiseur Intergalactique",
    class: "croiseur_intergalactique",
    img: "/images/enhanced/croiseur_intergalactique.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  croiseur: {
    name: "Croiseur",
    class: "croiseur",
    img: "/images/enhanced/croiseur.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  destroyer: {
    name: "Destroyer",
    class: "destroyer",
    img: "/images/enhanced/destroyer.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  dionysos: {
    name: "Dionysos",
    class: "dionysos",
    img: "/images/enhanced/dionysos.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  docker: {
    name: "Docker",
    class: "docker",
    img: "/images/enhanced/docker.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  enigma: {
    name: "Enigma",
    class: "enigma",
    img: "/images/enhanced/enigma.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  eros: {
    name: "Eros",
    class: "eros",
    img: "/images/enhanced/eros.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  fregate: {
    name: "Fregate",
    class: "fregate",
    img: "/images/enhanced/fregate.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  frozen: {
    name: "Frozen",
    class: "frozen",
    img: "/images/enhanced/frozen.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  helios: {
    name: "Helios",
    class: "helios",
    img: "/images/enhanced/helios.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  hera: {
    name: "Hera",
    class: "hera",
    img: "/images/enhanced/hera.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  hercules: {
    name: "Hercules",
    class: "hercules",
    img: "/images/enhanced/hercules.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  hermes: {
    name: "Hermes",
    class: "hermes",
    img: "/images/enhanced/hermes.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  intercepteur: {
    name: "Intercepteur",
    class: "intercepteur",
    img: "/images/enhanced/intercepteur.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  karfus: {
    name: "Karfus",
    class: "karfus",
    img: "/images/enhanced/karfus.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  legend: {
    name: "Legend",
    class: "legend",
    img: "/images/enhanced/legend.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  leviathan: {
    name: "Leviathan",
    class: "leviathan",
    img: "/images/enhanced/leviathan.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  loki: {
    name: "Loki",
    class: "loki",
    img: "/images/enhanced/loki.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  luna: {
    name: "Luna",
    class: "luna",
    img: "/images/enhanced/luna.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  mega_transporteur: {
    name: "Mega-Transporteur",
    class: "mega-transporteur",
    img: "/images/enhanced/mega_transporteur.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  minotaure: {
    name: "Minotaure",
    class: "minotaure",
    img: "/images/enhanced/minotaure.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  navette: {
    name: "Navette",
    class: "navette",
    img: "/images/enhanced/navette.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  nimbus: {
    name: "Nimbus",
    class: "nimbus",
    img: "/images/enhanced/nimbus.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  oblirator: {
    name: "Oblirator",
    class: "oblirator",
    img: "/images/enhanced/oblirator.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  odin: {
    name: "Odin",
    class: "odin",
    img: "/images/enhanced/odin.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  pallas: {
    name: "Pallas",
    class: "pallas",
    img: "/images/enhanced/pallas.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  patrouilleur: {
    name: "Patrouilleur",
    class: "patrouilleur",
    img: "/images/enhanced/patrouilleur.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  proleyend: {
    name: "Proleyend",
    class: "proleyend",
    img: "/images/enhanced/proleyend.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  proteus: {
    name: "Proteus",
    class: "proteus",
    img: "/images/enhanced/proteus.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  proto: {
    name: "Proto",
    class: "proto",
    img: "/images/enhanced/proto.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  saracen: {
    name: "Saracen",
    class: "saracen",
    img: "/images/enhanced/saracen.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  sonde: {
    name: "Sonde",
    class: "sonde",
    img: "/images/enhanced/sonde.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  station: {
    name: "Station",
    class: "station",
    img: "/images/enhanced/station.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  tethys: {
    name: "Tethys",
    class: "tethys",
    img: "/images/enhanced/tethys.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  thor: {
    name: "Thor",
    class: "thor",
    img: "/images/enhanced/thor.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  titan: {
    name: "Titan",
    class: "titan",
    img: "/images/enhanced/titan.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  transporteur: {
    name: "Transporteur",
    class: "transporteur",
    img: "/images/enhanced/transporteur.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  triton: {
    name: "Triton",
    class: "triton",
    img: "/images/enhanced/triton.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  tyran: {
    name: "Tyran",
    class: "tyran",
    img: "/images/enhanced/tyran.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  valkyrie: {
    name: "Valkyrie",
    class: "valkyrie",
    img: "/images/enhanced/valkyrie.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  virus: {
    name: "Virus",
    class: "virus",
    img: "/images/enhanced/virus.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  vortex: {
    name: "Vortex",
    class: "vortex",
    img: "/images/enhanced/vortex.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  voyager: {
    name: "Voyager",
    class: "voyager",
    img: "/images/enhanced/voyager.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
  zeus: {
    name: "Zeus",
    class: "zeus",
    img: "/images/enhanced/zeus.jpg",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
    },
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
    baseCoque: 1000,
  },
})

export default {
  getAllShips,
}
