import {
  TITANE,
  HYDROGENE,
  AZOTE,
  ALUMINUM,
  CUIVRE,
  FER,
  URANIUM,
  SILICIUM,
} from "./ResourcesService"

const getAllShips = () => ({
  apollo: {
    name: "Apollo",
    key: "apollo",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [HYDROGENE.name]: 100,
    },
    img: "/images/enhanced/apollo.jpg",
    emplacement: 10,
    fuel_space: 25_000,
    multiplier: {
      warp: 1,
      impulse: 1,
      conso: 1,
    },
  },
  arc: {
    name: "Arc",
    key: "arc",
    cost: {
      [TITANE.name]: 500,
      [CUIVRE.name]: 500,
      [AZOTE.name]: 8000,
      [HYDROGENE.name]: 100,
      [FER.name]: 100,
    },
    img: "/images/enhanced/arc.jpg",
    emplacement: 100,
    fuelSpace: 150_000,
    multiplier: {
      warp: 0.25,
      impulse: 0.3,
      conso: 15,
    },
  },
  //   "artemis",
  //   "athena",
  //   "atlas",
  //   "centaure",
  //   "chasseur",
  //   "croiseur_intergalactique",
  //   "croiseur",
  //   "destroyer",
  //   "dionysos",
  //   "docker",
  //   "enigma",
  //   "eros",
  //   "fregate",
  //   "frozen",
  //   "helios",
  //   "hera",
  //   "hercules",
  //   "hermes",
  //   "intercepteur",
  //   "karfus",
  //   "legend",
  //   "leviathan",
  //   "loki",
  //   "luna",
  //   "mega_transporteur",
  //   "minotaure",
  //   "navette",
  //   "nimbus",
  //   "oblirator",
  //   "odin",
  //   "pallas",
  //   "patrouilleur",
  //   "proleyend",
  //   "proteus",
  //   "proto",
  //   "saracen",
  //   "sonde",
  //   "station",
  //   "tethys",
  //   "thor",
  //   "titan",
  //   "transporteur",
  //   "triton",
  //   "tyran",
  //   "valkyrie",
  //   "virus",
  //   "vortex",
  //   "voyager",
  //   "zeus",
})

export default {
  getAllShips,
}
